# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Pokédex-Angular CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Utiliser Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Compiler le projet Angular
        run: npm run build --if-present

      - name: Installer Cypress
        run: npm install --save-dev cypress

      - name: Lancer le serveur local en arrière-plan
        run: npm install -g http-server && http-server dist/angular_project/browser -p 4200 &

      - name: Attendre que l'application soit disponible
        run: npx wait-on http://127.0.0.1:4200/

      - name: Exécuter les tests Cypress
        run: npx cypress run

      - name: Sauvegarder le dossier de build
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/

  # Déploiement CI/CD via Netlify
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Récupérer le dépôt
  #       uses: actions/checkout@v4

  #     - name: Télécharger le dossier de build
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: build-dist
  #         path: dist/

  #     - name: Installer Netlify CLI
  #       run: npm install -g netlify-cli

  #     - name: Déployer sur Netlify (sans rebuild)
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #       run: netlify deploy --prod --dir=dist/angular_project/browser --site=$NETLIFY_SITE_ID --no-build

  deploy: 
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Télécharger le dossier de build
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist/

      # - name: 📤 Déployer via FTP
      #   uses: sebastianpopp/ftp-action@releases/v2
      #   with:
      #     host: ${{ secrets.FTP_HOST }}
      #     user: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     localDir: ./dist
      #     remoteDir: /public_html/victor

      - name: Déployer en FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST_P }}
          user: ${{ secrets.FTP_USERNAME_P }}
          password: ${{ secrets.FTP_PASSWORD_P }}
          localDir: ./dist/angular_project/browser
          remoteDir: /