# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js CI & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Utiliser Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Installer les dépendances
        run: npm ci

      - name: Compiler le projet
        run: npm run build --if-present

      - name: Lancer le serveur en arrière-plan
        run: npm install -g http-server && http-server dist/angular_project/browser -p 4200 &

      - name: Attendre que l'application soit disponible
        run: npx wait-on http://127.0.0.1:4200/

      - name: Exécuter les tests Cypress
        run: npx cypress run

      - name: Sauvegarder le dossier de build
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@v4

      - name: Télécharger le dossier de build
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist/

      - name: Installer Netlify CLI
        run: npm install -g netlify-cli

      - name: Builder
        run: npm run build

      - name: Lancer le serveur en arrière-plan
        run: npm install -g http-server && http-server dist/angular_project/browser &

      - name: Attendre que l'application soit disponible
        run: npx wait-on https://pokedex-gular.netlify.app/
        
      - name: Déployer sur Netlify
        env:
          NETLIFY_AUTH_TOKEN: nfp_g6Fb1Jyh1VwyY1WnFZmnVKtwusHUNBgbeaf0
          NETLIFY_SITE_ID: 628adf1e-5479-4b8f-a9c5-ec8ddf245f98
        run: netlify deploy --prod --dir=dist/angular_project/browser --site=$NETLIFY_SITE_ID
